/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package utlis;

import application.Parametre;
import application.ResultSetTableModel;
import application.BDD;
import application.Cash;
import application.Product;
import application.UtilsFonction;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author eyfal
 */
public class Cachier extends javax.swing.JFrame {

    /**
     * Creates new form Cachier
     */
        ResultSet rs;
    BDD db;
    int old, dec, now;
    public Cachier() {
        db = new BDD(new Parametre().HOST_DB, new Parametre().USERNAME_DB, new Parametre().PASSWORD_DB, new Parametre().IPHOST, new Parametre().PORT);
        initComponents();
        table();
        jam();
    }
        public void table() {
        List<Product> listProdut = new ArrayList<>();
        try {
        String colon[] = {"code_produit","reference","designation","rangement","fournisseur","remise","prix","stock"};
        rs = db.querySelectAll("produit");
                    while(rs.next()){
                Product p = new Product();
                p.setId(rs.getInt("id"));
                p.setCode_produit(rs.getInt("code_produit"));
                p.setReference(rs.getString("reference"));
                p.setPasdesignationsword(rs.getString("designation"));
                p.setRangement(rs.getString("rangement"));
                p.setFournisseur(rs.getString("fournisseur"));
                p.setRemise(rs.getInt("remise"));
                p.setPrix(rs.getInt("prix"));
                p.setStock(rs.getInt("stock"));
                listProdut.add(p);
            }
            UtilsFonction.displayDataInTable(listProdut, table_prod, List.of("id"));
            } catch (SQLException ex) {
            Logger.getLogger(Produit.class.getName()).log(Level.SEVERE, null, ex);
        }
        //table_prod.setModel(new ResultSetTableModel(rs));
    }
        public void importer() {
        List<Cash> listCas = new ArrayList<>();
        try {
        String colon[] = {"num_facture","code_produit","reference","prix_vente","stock_sortie","subtotal"};
        rs = db.querySelectAll("vente", "num_facture='" + txt_fac.getText() + "'");
                while(rs.next()){
                Cash c = new Cash();
                c.setNum_facture(rs.getString("num_facture"));
                c.setCode_produit(rs.getString("code_produit"));
                c.setReference(rs.getString("reference"));
                c.setPrix_vente(rs.getString("prix_vente"));
                c.setStock_sortie(rs.getString("stock_sortie"));
                c.setSubtotal(rs.getInt("subtotal"));
                listCas.add(c);
            }
                UtilsFonction.displayDataInTable(listCas, table_ven);
            } catch (SQLException ex) {
            Logger.getLogger(Cash.class.getName()).log(Level.SEVERE, null, ex);
        }
        //table_ven.setModel(new ResultSetTableModel(rs));
    }
        public void jam() {
        Date s = new Date();
        SimpleDateFormat tgl = new SimpleDateFormat("EEEE-dd-MMM-yyyy");
        SimpleDateFormat jam = new SimpleDateFormat("HH:mm");
        lbl1.setText(jam.format(s));
        lbl2.setText(tgl.format(s));}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_prod = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        com_rech = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txt_rech = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lbltot1 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txt_co = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txt_ref = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_ra = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_fou = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_pri = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_rem = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txt_des = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_sto = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_ven = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        txt_fac = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        lbltot2 = new javax.swing.JLabel();
        txt_cas = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txt_pay = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        lbl1 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 1050));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setForeground(new java.awt.Color(0, 51, 51));
        jPanel1.setLayout(null);

        table_prod.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "code_produit", "designation", "reference", "rangement", "fournisseur", "remise", "prix", "stock"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        table_prod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_prodMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_prod);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(0, 40, 860, 80);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Cashier");
        jLabel3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel3);
        jLabel3.setBounds(350, 10, 100, 30);

        com_rech.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "id", "code_produits", "reference", "designation", "rangement", "fournisseur", "remise", "prix", "stock" }));
        jPanel1.add(com_rech);
        com_rech.setBounds(210, 130, 109, 30);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Recherche par Catégorie");
        jLabel2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 130, 202, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 0, 870, 190);

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setForeground(new java.awt.Color(0, 102, 102));
        jPanel2.setLayout(null);
        jPanel2.add(txt_rech);
        txt_rech.setBounds(160, 10, 120, 30);

        jLabel14.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel14.setText("RP : ");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(40, 390, 50, 30);

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setText("Ajouter au produit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(50, 430, 190, 30);

        lbltot1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        lbltot1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltot1.setText("0");
        jPanel2.add(lbltot1);
        lbltot1.setBounds(110, 390, 170, 30);

        jButton5.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 153, 153));
        jButton5.setText("Rechercher");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5);
        jButton5.setBounds(0, 10, 121, 32);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel9.setText("code_produit :");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(0, 70, 100, 17);

        txt_co.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_coActionPerformed(evt);
            }
        });
        jPanel2.add(txt_co);
        txt_co.setBounds(120, 60, 160, 30);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel12.setText("reference     :");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(0, 110, 100, 17);

        txt_ref.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_refActionPerformed(evt);
            }
        });
        jPanel2.add(txt_ref);
        txt_ref.setBounds(120, 100, 160, 30);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("rangement :");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(0, 150, 100, 17);

        txt_ra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_raActionPerformed(evt);
            }
        });
        jPanel2.add(txt_ra);
        txt_ra.setBounds(120, 140, 160, 30);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText("fournisseur :");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(0, 190, 100, 17);

        txt_fou.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_fouActionPerformed(evt);
            }
        });
        jPanel2.add(txt_fou);
        txt_fou.setBounds(120, 180, 160, 30);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Prix        :");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(0, 230, 100, 17);

        txt_pri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_priActionPerformed(evt);
            }
        });
        jPanel2.add(txt_pri);
        txt_pri.setBounds(120, 220, 160, 30);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setText("remise     :");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(0, 280, 100, 17);

        txt_rem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_remActionPerformed(evt);
            }
        });
        jPanel2.add(txt_rem);
        txt_rem.setBounds(120, 270, 160, 30);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel13.setText("designation :");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(0, 320, 100, 17);

        txt_des.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_desActionPerformed(evt);
            }
        });
        jPanel2.add(txt_des);
        txt_des.setBounds(120, 310, 160, 30);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel10.setText("Stock sortire  :");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(0, 360, 100, 17);

        txt_sto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_stoActionPerformed(evt);
            }
        });
        txt_sto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_stoKeyReleased(evt);
            }
        });
        jPanel2.add(txt_sto);
        txt_sto.setBounds(120, 350, 160, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 190, 330, 470);

        jPanel3.setLayout(null);

        jLabel16.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel16.setText("Vente");
        jLabel16.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel3.add(jLabel16);
        jLabel16.setBounds(230, 10, 100, 30);

        table_ven.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "num_facture", "code_produit", "reference", "Prix de vente", "Stock sortire", "total "
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(table_ven);

        jPanel3.add(jScrollPane2);
        jScrollPane2.setBounds(0, 90, 530, 110);

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel15.setText("Num de facture :");
        jPanel3.add(jLabel15);
        jLabel15.setBounds(0, 60, 100, 17);

        txt_fac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_facActionPerformed(evt);
            }
        });
        jPanel3.add(txt_fac);
        txt_fac.setBounds(110, 50, 160, 30);

        jButton3.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jButton3.setText("recherche ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3);
        jButton3.setBounds(280, 50, 120, 24);

        jButton4.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jButton4.setText("Supprimer");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4);
        jButton4.setBounds(410, 50, 110, 24);

        jLabel21.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Total ");
        jPanel3.add(jLabel21);
        jLabel21.setBounds(100, 200, 110, 30);

        jLabel19.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Rp");
        jPanel3.add(jLabel19);
        jLabel19.setBounds(240, 200, 70, 30);

        lbltot2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        lbltot2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltot2.setText("0");
        jPanel3.add(lbltot2);
        lbltot2.setBounds(320, 200, 190, 30);

        txt_cas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_casKeyReleased(evt);
            }
        });
        jPanel3.add(txt_cas);
        txt_cas.setBounds(90, 230, 130, 30);

        jLabel20.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("cash :");
        jPanel3.add(jLabel20);
        jLabel20.setBounds(30, 230, 50, 30);

        jLabel18.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("payé aprés :");
        jPanel3.add(jLabel18);
        jLabel18.setBounds(240, 230, 90, 30);
        jPanel3.add(txt_pay);
        txt_pay.setBounds(350, 230, 130, 30);

        jButton2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton2.setText("imprimer");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);
        jButton2.setBounds(100, 270, 350, 30);

        jButton6.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton6.setText("annuler");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton6);
        jButton6.setBounds(100, 310, 350, 30);

        lbl1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl1.setText("jLabel12");
        jPanel3.add(lbl1);
        lbl1.setBounds(390, 10, 45, 15);

        lbl2.setText("jLabel17");
        jPanel3.add(lbl2);
        lbl2.setBounds(400, 30, 43, 16);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(340, 190, 530, 470);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if (txt_rech.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "SVP entrer quelque chose");
        } else {
            if (com_rech.getSelectedItem().equals("code_produit")) {
                rs = db.querySelectAll("produit", "code_produit LIKE '%" + txt_rech.getText() + "%' ");
                table_prod.setModel(new ResultSetTableModel(rs));
            } else if (com_rech.getSelectedItem().equals("reference")) {
                rs = db.querySelectAll("produit", "reference LIKE '%" + txt_rech.getText() + "%' ");
                table_prod.setModel(new ResultSetTableModel(rs));
            } else if (com_rech.getSelectedItem().equals("deseignation")) {
                rs = db.querySelectAll("produit", "deseignation LIKE '%" + txt_rech.getText() + "%' ");
                table_prod.setModel(new ResultSetTableModel(rs));
            } else if (com_rech.getSelectedItem().equals("rangement")) {
                rs = db.querySelectAll("produit", "rangement LIKE '%" + txt_rech.getText() + "%' ");
                table_prod.setModel(new ResultSetTableModel(rs));
            } else if (com_rech.getSelectedItem().equals("fournisseur")) {
                rs = db.querySelectAll("produit", "fournisseur LIKE '%" + txt_rech.getText() + "%' ");
                table_prod.setModel(new ResultSetTableModel(rs));
            } else if (com_rech.getSelectedItem().equals("remise")) {
                rs = db.querySelectAll("produit", "remise LIKE '%" + txt_rech.getText() + "%' ");
                table_prod.setModel(new ResultSetTableModel(rs));
            } else if (com_rech.getSelectedItem().equals("prix")) {
                rs = db.querySelectAll("produit", "prix LIKE '%" + txt_rech.getText() + "%' ");
                table_prod.setModel(new ResultSetTableModel(rs));
            } else if (com_rech.getSelectedItem().equals("stock")) {
                rs = db.querySelectAll("produit", "stock LIKE '%" + txt_rech.getText() + "%' ");
                table_prod.setModel(new ResultSetTableModel(rs));

            }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void txt_facActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_facActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_facActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        importer();
        total();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String id = String.valueOf(table_ven.getValueAt(table_ven.getSelectedRow(), 0));
        if (JOptionPane.showConfirmDialog(this, "est ce que tu es sure que tu veux supprimer ", "Attention", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
            db.queryDelete("vente", "id=" + id);
        } else {
            return;
        }
        importer();
        total();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txt_casKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_casKeyReleased
        payaprés();        // TODO add your handling code here:
    }//GEN-LAST:event_txt_casKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Recu n = new Recu();
        n.setVisible(true);
        payaprés();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        String invoice = txt_fac.getText();
        if (JOptionPane.showConfirmDialog(this,"est ce que tu es sure que tu veux supprimer ","attention", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
            db.queryDelete("vente", "num_facture=" + invoice);
        } else {
            return;
        }
        importer();
        total();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (txt_co.getText().equals("") || txt_ref.getText().equals("") || txt_ra.getText().equals("")
                || txt_fou.getText().equals("") || txt_pri.getText().equals("") || txt_pri.getText().equals("") || txt_des.getText().equals("")|| txt_sto.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "SVP entrer vos donneé");
        } else if (txt_fac.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "SVP entrer le num de facture");
        } else {
            String[] colon = {"num_facture","code_produit", "reference", "prix_vente", "stock_sortie", "subtotal"};
            String[] isi = {txt_fac.getText(), txt_co.getText(), txt_ref.getText(), txt_des.getText(), txt_sto.getText(), lbltot1.getText()};
            System.out.println(db.queryInsert("vente", colon, isi));
            try {
                if (!test_stock()) { 
                    JOptionPane.showMessageDialog(this, "le stock est Limiter");
                } else {
                    def(); //true
                    table(); //true
                }
            } catch (SQLException ex) {
                Logger.getLogger(Cachier.class.getName()).log(Level.SEVERE, null, ex);
                System.err.println("\n"+ex);
            }
            subtotal();
            importer();
            total();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void table_prodMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_prodMouseClicked
txt_co.setText(String.valueOf(table_prod.getValueAt(table_prod.getSelectedRow(), 1)));
txt_des.setText(String.valueOf(table_prod.getValueAt(table_prod.getSelectedRow(), 2)));
txt_ref.setText(String.valueOf(table_prod.getValueAt(table_prod.getSelectedRow(), 3)));
txt_ra.setText(String.valueOf(table_prod.getValueAt(table_prod.getSelectedRow(), 4)));
txt_fou.setText(String.valueOf(table_prod.getValueAt(table_prod.getSelectedRow(), 5)));
txt_pri.setText(String.valueOf(table_prod.getValueAt(table_prod.getSelectedRow(), 6)));
txt_pri.setText(String.valueOf(table_prod.getValueAt(table_prod.getSelectedRow(), 7)));
txt_sto.setText(String.valueOf(table_prod.getValueAt(table_prod.getSelectedRow(), 8)));
    }//GEN-LAST:event_table_prodMouseClicked

    private void txt_coActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_coActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_coActionPerformed

    private void txt_refActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_refActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_refActionPerformed

    private void txt_raActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_raActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_raActionPerformed

    private void txt_fouActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_fouActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_fouActionPerformed

    private void txt_priActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_priActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_priActionPerformed

    private void txt_remActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_remActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_remActionPerformed

    private void txt_desActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_desActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_desActionPerformed

    private void txt_stoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_stoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_stoActionPerformed

    private void txt_stoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_stoKeyReleased
        subtotal();        // TODO add your handling code here:
    }//GEN-LAST:event_txt_stoKeyReleased

    /**
     * @param args the command line arguments
     */
        public void cout() {
        double a = Double.parseDouble(txt_pri.getText());
        double b = Double.parseDouble(txt_pri.getText());
        double c = a - a * (b / 100);
        txt_des.setText(String.valueOf(c));
    }
             public void subtotal() {
        double a = Double.parseDouble(txt_pri.getText());
        double b = Double.parseDouble(txt_sto.getText());
        double c = a * b;
        lbltot1.setText(String.valueOf(c));}
        public void total() {
        rs = db.exécutionQuery("SELECT SUM(subtotal) as subtotal FROM vente WHERE num_facture = '" + txt_fac.getText() + "'");
        try {
            rs.next();
            lbltot2.setText(rs.getString("subtotal"));
        } catch (SQLException ex) {
            Logger.getLogger(Cachier.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
               public boolean test_stock() throws SQLException {
        boolean teststock;
        rs = db.querySelectAll("produit","code_produit='" + txt_co.getText() + "'");
        while (rs.next()) {
            old = rs.getInt("stock");
        }
        dec = Integer.parseInt(txt_sto.getText());
        if (old < dec) {
            teststock = false;
        } else {
            teststock = true;
        }
        return teststock;
    }
    public void def() throws SQLException {
        rs = db.querySelectAll("produit", "code_produit='" + txt_co.getText() + "'");
        while (rs.next()) {
            old = rs.getInt("stock");
        }
        dec = Integer.parseInt(txt_sto.getText());
        now = old - dec;
         String nvstock = Integer.toString(now);

        String a = String.valueOf(nvstock);
        String[] colon = {"stock"};
        String[] isi = {a};
        System.out.println(db.queryUpdate("produit", colon, isi, "code_produit='" + txt_co.getText() + "'"));
    }
        public void payaprés() {
        int a = Integer.parseInt(lbltot2.getText());
        int b = Integer.parseInt(txt_cas.getText());
        int c = b - a;
        txt_pay.setText(Integer.toString(c));
    }
    
             
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cachier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cachier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cachier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cachier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cachier().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> com_rech;
    private javax.swing.JButton jButton1;
    public static javax.swing.JButton jButton2;
    public static javax.swing.JButton jButton3;
    public static javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    public static javax.swing.JButton jButton6;
    public static javax.swing.JLabel jLabel10;
    public static javax.swing.JLabel jLabel12;
    public static javax.swing.JLabel jLabel13;
    public static javax.swing.JLabel jLabel14;
    public static javax.swing.JLabel jLabel15;
    public static javax.swing.JLabel jLabel16;
    public static javax.swing.JLabel jLabel18;
    public static javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    public static javax.swing.JLabel jLabel20;
    public static javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    public static javax.swing.JLabel jLabel4;
    public static javax.swing.JLabel jLabel6;
    public static javax.swing.JLabel jLabel7;
    public static javax.swing.JLabel jLabel8;
    public static javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JLabel lbl1;
    public static javax.swing.JLabel lbl2;
    public static javax.swing.JLabel lbltot1;
    public static javax.swing.JLabel lbltot2;
    private javax.swing.JTable table_prod;
    public static javax.swing.JTable table_ven;
    public static javax.swing.JTextField txt_cas;
    public static javax.swing.JTextField txt_co;
    public static javax.swing.JTextField txt_des;
    public static javax.swing.JTextField txt_fac;
    public static javax.swing.JTextField txt_fou;
    public static javax.swing.JTextField txt_pay;
    public static javax.swing.JTextField txt_pri;
    public static javax.swing.JTextField txt_ra;
    private javax.swing.JTextField txt_rech;
    public static javax.swing.JTextField txt_ref;
    public static javax.swing.JTextField txt_rem;
    public static javax.swing.JTextField txt_sto;
    // End of variables declaration//GEN-END:variables
}
